### PR TITLE
Implemented the spec and unittests

### PR DESCRIPTION
**Pull request by bferdinandus**
Here's the full implementation and unittests to back it up. I (unit)tested on adobe coldfusion and Lucee coldfusion. No gitflow implemented just yet. I have never worked with that so it will take more time to figure out. It should be possible to run the unittests automatically with the git flows. Would you like me to implement that before or after this PR has been reviewed?

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @bferdinandus,

Thank you for the PR and the unit tests. It's a new repo, so it's fine if we just push to `main` as this is figured out. I've merged your PR and sent you a maintainer invite - so feel free to push as you see fit.

A few follow-up items:
- Feel free to add Github Actions testing, if it's available for ColdFusion (I'm not sure myself)
- I also noticed the text change: isn't it `ColdFusion` as opposed to `Coldfusion`?

I'll update the website. Thank you for the good work!

**Comment by timsayshey** [comment]
Great job on this! Much better than my first attempt :)

**Comment by bferdinandus** [comment]
> * I also noticed the text change: isn't it `ColdFusion` as opposed to `Coldfusion`?

Yes you are right. It should be `ColdFusion`. I'll fix that in the near future.

**Comment by bferdinandus** [comment]
> Feel free to add Github Actions testing, if it's available for ColdFusion (I'm not sure myself)

I have added a github workflow to automatically run the unittests on differend ColdFusion engines. I also added a badge in the readme file to show the status of the tests.

**Comment by 4kimov** [comment]
@bferdinandus I saw, nice 💪 Good job!

**Pull request merged**
